export const String = {
  START_UP: 'Start Up',
  INVESTOR: 'Investor',
  CONSILTANT: 'Consultant',
  ANGEL_NET: 'Angel Network',
  INV_BANK: 'Investing Bank',
  ACCE_INCU: 'Accelerator / Incubator',
  SIGN_UP_TXT: "We're excited to have you on board, Let's get started by creating your account",
  WELCOME: 'Welcome to Arthasaga',
  I_AM: 'I am a/an',
  COPY_RIGHT: '© 2023 Arthasaga pvt ltd. All Rights Reserved.',
  ENTER_YOUR_START_UP: 'Enter your StartUp Name',
  START_UP_MAX: 'Startup name is required (max 50 characters allowed)',
  MAX_50: 'max 50 characters allowed',
  LEGAL_NAME: 'Legal Name is required',
  LEGAL_NAME_MAX: 'Legal name is required (max 100 characters allowed)',
  MAX_100: 'max 100 characters allowed',
  FOUNDER_NAME: 'Enter your Founder Name',
  NAME_REQ: 'Founder Name is required',
  EMAIL_UP: 'Enter your email',
  VALID_EMAIL: 'Please enter a valid email',
  VALID_EMAIL_REQ: 'Email is required',
  AADHAR_NUM: 'Enter your aadhar number',
  AADHAR_NUM_VALID:
    /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/,
  AADHAR_NUM_VALID_IS: 'aadhar number is not valid',
  CIN_NUM: 'Enter CIN number',
  CIN_NUM_VALID: /^([LUu]{1})([0-9]{5})([A-Za-z]{2})([0-9]{4})([A-Za-z]{3})([0-9]{6})$/,
  VALID_NAME: 'Please enter a valid phone number ',
  PASSWORD: 'Enter your password',
  PASSWORD_LEN: 'Password should be of minimum 8 characters length',
  PASSWORD_REQ: 'Password is required',
  NAME: 'Enter Your Name',
  ENTER_RESIDENCE: 'Enter Your Residence',
  INVESTOR_FOOTER: 'Investments',
  RESOURCE: 'Resources',
  COMPANY: 'Company',
};
